version: "2.4"

services:
  jekyll:
    image: local-eduherminio.github.io
    command: bundle exec jekyll serve --force_polling --future --draft -H 0.0.0.0 -P 4000
    volumes:
      - .:/site
    ports:
      - "8080:4000"
