on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron:  '1 0 * * 1' 

name: CI
jobs:
  linkinator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: JustinBeckwith/linkinator-action@v1
        with:
          paths: "**/*.md"
          markdown: true
          retry: true
          linksToSkip: "https://github.com/mmistakes/mm-github-pages-starter/generate, https://linkhelp.clients.google.com/tbproxy/lh/wm/fixurl.js"